# Generated by Django 3.2.7 on 2021-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start_station_id', models.CharField(max_length=5)),
                ('end_station_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Train_to_Station',
            fields=[
                ('station_id', models.CharField(max_length=5)),
                ('train_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
