# Generated by Django 3.2.7 on 2021-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Station_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_id', models.CharField(max_length=5)),
                ('end_station_id', models.CharField(max_length=5)),
            ],
        ),
    ]
